### PR TITLE
fix: use env variable for project deletion cool off period

### LINKED ISSUE #493: project deletion - update confirmation message
Currently, once a project is deleted, it is stored in the "Trash" folder for 30 days where the user can restore it. This should be clarified in the delete message

image

### PR DESCRIPTION
**Pull request by NRayya**
Fixes #493

### CODE REVIEW

File: app/Http/Middleware/HandleInertiaRequests.php [hunk 1]
```diff
@@ -72,6 +72,7 @@ public function share(Request $request)
             'SCOUT_PREFIX' => (env('SCOUT_PREFIX')),
             'europemcWSApi' => (env('EUROPEMC_WS_API')),
             'dataciteURL' => env('DATACITE_ENDPOINT'),
+            'collOffPeriod' => env('COOL_OFF_PERIOD'),
```
Comment (NishaSharma14) [inline app/Http/Middleware/HandleInertiaRequests.php:75]: spelling check `coolOffPeriod`

File: resources/js/Pages/Project/Partials/Delete.vue [hunk 2]
```diff
@@ -35,8 +35,8 @@
                             time before they are permanently deleted. Please
                             enter your password to confirm you would like to
                             delete your project, and if there is no action in
-                            the next 30 days, the project will be deleted
-                            permanently.
+                            the next {{ collOffPeriod }} days, the project will
```
Comment (NishaSharma14) [inline resources/js/Pages/Project/Partials/Delete.vue:38]: `coolOffPeriod`

**Review by NishaSharma14 — CHANGES_REQUESTED** [review]

**Review by NishaSharma14 — APPROVED** [review]

File: app/Http/Middleware/HandleInertiaRequests.php (hunk 1 above)
Comment (NishaSharma14) [inline app/Http/Middleware/HandleInertiaRequests.php:75]: This is still unchanged
