### PR TITLE
Fixes License issue.

### LINKED ISSUE #254: Updating the license of a study needs reloading to show up
**Describe the bug**
When going to "view details" of a study, and change the license there and press save, the changes don't reflect in the study without reloading

### PR DESCRIPTION
**Pull request by NishaSharma14**
Fixes #254

### CODE REVIEW

File: app/Http/Controllers/StudyController.php [hunk 1]
```diff
@@ -20,9 +20,16 @@
 use Inertia\Inertia;
 use Laravel\Fortify\Actions\ConfirmPassword;
 use Laravel\Jetstream\Jetstream;
+use App\Http\Controllers\Admin\LicenseController;
 
 class StudyController extends Controller
 {
```
Comment (CS76) [inline app/Http/Controllers/StudyController.php:26]: Move to actions

**Review by CS76 — CHANGES_REQUESTED** [review]

**Review by CS76 — APPROVED** [review]
