### PR TITLE
fix: add sender's details in project invite mail

### LINKED ISSUE #656: Add invitation sender details to the invitation email
Add the details of the person sending the invitation to the email.

image

### PR DESCRIPTION
**Pull request by NishaSharma14**
Fixes #656

### CODE REVIEW

**Comment by NishaSharma14** [comment]
image

File: app/Actions/Project/InviteProjectMember.php [hunk 1]
```diff
@@ -34,6 +34,7 @@ public function invite($user, $project, string $email, string $role = null, stri
             'email' => $email,
             'role' => $role,
             'message' => $message,
+            'invited_by' => $user->id,
```
Comment (CS76) [inline app/Actions/Project/InviteProjectMember.php:37]: Pass the user name and concatenate the name directly to avoid additional DB query

File: resources/views/vendor/mail/study-invitation.blade.php [hunk 2]
```diff
@@ -1,5 +1,5 @@
 @component('mail::message')
-{{ __('You have been invited to join the :study study!', ['study' => $invitation->study->name]) }}
+{{ __('You have been invited to join the study **:study** by :invitedBy as role :role', ['study' => $invitation->study->name, 'invitedBy' => $invitedBy,'role' => $invitation->role]) }}
```
Comment (CS76) [inline resources/views/vendor/mail/study-invitation.blade.php:2]: {{ __('You have been invited to join (role: :role) the study **:study** by :invitedBy', ['study' => $invitation->study->name, 'invitedBy' => $invitedBy,'role' => $invitation->role]) }}

**Review by CS76 — CHANGES_REQUESTED** [review]

**Comment by NishaSharma14** [comment]
image

**Review by CS76 — APPROVED** [review]
