### PR TITLE
fix: extract doi from URL.

### LINKED ISSUE #775: citations import - enable importing from doi full link
With "https://doi.org/10.1002/mrc.4782" we get an error while "10.1002/mrc.4782" import works

image

Same thing happens when importing authors from article doi

### PR DESCRIPTION
**Pull request by NishaSharma14**
fixes #775

### CODE REVIEW

File: resources/js/Mixins/Global.js [hunk 1]
```diff
@@ -113,6 +113,15 @@ export default {
...
         },
+
+        /*Extract Doi from URL*/
+        extractDoi(query) {
+            query = query.trim();
+            if (query.indexOf("https://doi.org/") > -1) {
+                query = query.substr(16);
+            }
+            return query;
+        },
```
Comment (CS76) [inline resources/js/Mixins/Global.js:124]: Use URL module to extract path and then sanitise the DOI before updating the input based on onblur event

**Review by CS76 — CHANGES_REQUESTED** [review]

File: resources/js/Mixins/Global.js (hunk 1 above)
Comment (NishaSharma14) [reply resources/js/Mixins/Global.js]:
```
        extractDoi(query) {
            if(query.indexOf("http") > -1){
                var url = new URL(query);
                query = (url.pathname).replace('/','');
            }
            return query.trim();
        },
```
